### ISSUE TITLE
No module named main

### ISSUE THREAD

**Issue by mehdibaha** [architv/soccer-cli#1]
After successfully installing soccer-cli, this is the traceback error I'm getting when trying to use it

```
Traceback (most recent call last):
  File "C:\x\x\Anaconda\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\x\x\Anaconda\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\x\x\Anaconda\Scripts\soccer.exe\__main__.py", line 5, in <module>
ImportError: No module named main
```

Thanks !

**Comment by architv** [comment]
Seems like you are using windows. I didn't test it out on that. Let me test it out on windows I will let you know.

**Comment by Heart1010** [comment]
I append this issue ticket here with another one I get on win10 powershell.
```python
PS C:\Users\Hermann> soccer --standings --league=BL
POS     CLUB                              PLAYED        GOAL DIFF     POINTS
Traceback (most recent call last):
  File "C:\Users\Hermann\AppData\Local\Programs\Python\Python35\Scripts\soccer-script.py", line 9, in <module>
    load_entry_point('soccer-cli==0.0.2.4', 'console_scripts', 'soccer')()
  File "C:\Users\Hermann\AppData\Local\Programs\Python\Python35\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Hermann\AppData\Local\Programs\Python\Python35\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "C:\Users\Hermann\AppData\Local\Programs\Python\Python35\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Hermann\AppData\Local\Programs\Python\Python35\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Hermann\AppData\Local\Programs\Python\Python35\Scripts\main.py", line 179, in main
    get_standings(league)
  File "C:\Users\Hermann\AppData\Local\Programs\Python\Python35\Scripts\main.py", line 92, in get_standings
    print_standings(req.json())
  File "C:\Users\Hermann\AppData\Local\Programs\Python\Python35\Scripts\main.py", line 108, in print_standings
    goaldiff=str(team["goalDifference"]), points=str(team["points"])
TypeError: non-empty format string passed to object.__format__
````
Every other command is working perfect, only ```--standings``` lead to this error message.

**Comment by architv** [comment]
Hi @Heart1010 ! Unfortunately, I don't have a windows machine and I am not able to reproduce this error on my linux. It would be nice if someone in the community could help me with this.

**Comment by thurask** [comment]
Latest git, cmd on Windows 10, Python 2.7.10 (Anaconda):

```
[py2] C:\Users\thurask\git\soccer-cli>soccer --standings --league=BL
POS     CLUB                              PLAYED        GOAL DIFF     POINTS
1       Borussia Dortmund                 3             10            9
2       FC Bayern M├╝nchen                3             9             9
3       VfL Wolfsburg                     3             4             7
4       1. FC K├╢ln                       3             3             7
5       1. FSV Mainz 05                   3             3             6
6       Bayer Leverkusen                  3             -1            6
7       FC Ingolstadt 04                  3             -2            6
8       Eintracht Frankfurt               3             2             4
9       FC Schalke 04                     3             0             4
10      Hertha BSC                        3             -1            4
11      Werder Bremen                     3             -2            4
12      SV Darmstadt 98                   3             0             3
13      Hamburger SV                      3             -5            3
14      TSG 1899 Hoffenheim               3             -2            1
15      FC Augsburg                       3             -2            1
16      Hannover 96                       3             -4            1
17      VfB Stuttgart                     3             -6            0
18      Bor. M├╢nchengladbach             3             -6            0
```

**Comment by architv** [comment]
Thanks @thurask for clearing it out. @Heart1010 the package isn't `python3.x` compatible, you'll need to use it with `python2.x`. Let me know if that resolves the issue.

**Comment by Heart1010** [comment]
http://stackoverflow.com/questions/29613676/python-typeerror-non-empty-format-string-passed-to-object-format

2015-09-02 21:49 GMT+02:00 Archit Verma <notifications@github.com>:

**Comment by nare469** [comment]
@Heart1010 if you change `team=u''.join(team["teamName"]).encode('utf-8')` to just `team["teamName"]`, in the `print_standings` function in `main.py`, it should work fine in python3.

**Comment by FreddieV4** [comment]
I'm having the same issue but in Python 2.7 ![](http://puu.sh/jXSwm/e08c179a9c.png)

**Comment by Heart1010** [comment]
@nare469 Thanks!

**Comment by cirrusUK** [comment]
Hi, Thanks for this, i hope we get it working soon, i have similar issue, im using Archlinux and on launch i get ..

cirrus  blade  soccer-cli  soccer --standings --league=EPL
Traceback (most recent call last):
  File "/usr/bin/soccer", line 9, in <module>
    load_entry_point('soccer-cli==0.0.5.0', 'console_scripts', 'soccer')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 568, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2720, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2380, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/soccer/main.py", line 21, in <module>
ImportError: No module named config
 cirrus  blade  soccer-cli  
regards
(sorry my programming skills are limited to 5 line shell scripts)

**Comment by cirrusUK** [comment]
heh i fixed my error by simply sourcing my ~/.zshrc  where i point to the API key, after sourcing it works great, i LOVE it, thanks brogrammer.

**Comment by haiya512** [comment]
@cirrusUK   where is the command "w3m"?
