### ISSUE TITLE
ImportError: No module named 'leagueids'

### ISSUE THREAD

**Issue by tvk7** [architv/soccer-cli#52]
Hello, after building from git, I get:

Traceback (most recent call last):
  File "/usr/bin/soccer", line 9, in <module>
    load_entry_point('soccer-cli==0.0.5.0', 'console_scripts', 'soccer')()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2697, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2370, in load
    return self.resolve()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2376, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.5/site-packages/soccer_cli-0.0.5.0-py3.5.egg/soccer/main.py", line 6, in <module>
ImportError: No module named 'leagueids'

Maybe its a problem with Python Version. I have also Python 2.7 installed, how can I force the setup.py to use this?

**Comment by Saturn** [comment]
You should be able to do `python2.7 setup.py install`.

**Comment by tvk7** [comment]
This helped. Thanks...
